[tool.poetry]
name = "hifive_filler"
version = "0.2.25"
description = ""
authors = ["yusata","piyochee","hnakatan","floening"]

[tool.poetry.dependencies]
python = "3.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
hifive_filler = "hifive_filler.main:main"