[tool.poetry]
name = "caspius"
version = "1.2"
description = "Simple log system for python"
authors = ["Dan Gost <dangost16@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
